services:
  app:
    build:
      context: .
    ports:
      - "3002:3032"
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

